apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: rethinkdbclusters.rethinkdb.com
spec:
  group: rethinkdb.com
  names:
    kind: RethinkDBCluster
    listKind: RethinkDBClusterList
    plural: rethinkdbclusters
    singular: rethinkdbcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            pod:
              properties:
                persistentVolumeClaimSpec:
                  type: object
                resources:
                  type: object
              type: object
            size:
              format: int32
              type: integer
            version:
              type: string
            webAdminEnabled:
              type: boolean
          required:
          - size
          - version
          - webAdminEnabled
          type: object
        status:
          properties:
            servers:
              items:
                type: string
              type: array
            serviceName:
              type: string
          required:
          - servers
          - serviceName
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
