kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rethinkdb-operator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-rethinkdb-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: rethinkdb-operator
  apiGroup: rbac.authorization.k8s.io
