apiVersion: rethinkdb.com/v1alpha1
kind: RethinkDBCluster
metadata:
  name: rethinkdb-limits-example
  labels:
    tier: backend
spec:
  size: 3
  webAdminEnabled: true
  pod:
    resources:
      limits:
        cpu: 1.0
        memory: 3Gi
      requests:
        cpu: 0.3
        memory: 2Gi
